#!/bin/bash
: '
    Utility to host new website on apaache server.

'

#User needs to enter the domain name
#DOMAIN_NAME="test.org"


usage(){
    echo ""
    echo "host_website <domain_name>"
    echo ""
    echo "<domain_name>   : any valid domain name <test.com>"
    echo ""
    echo ""
}

if [ $# -lt 1 ]; then
    echo
    echo "[ error ] usage "
    usage
    exit 1
fi

DOMAIN_NAME="$1"
DOCUMENT_ROOT="/var/www"

#Apache config directory - It may change for different versions of apache
APACHE_CONFIG_DIR="/etc/apache2/sites-available"
CONFIG_FILE="$DOMAIN_NAME.conf"

CONFIG_FILE_WP="$APACHE_CONFIG_DIR/$CONFIG_FILE"

#Copy configuration to config file
echo "[ status ] Create Apache Config For Domain Name ( $DOMAIN_NAME )"
cat > $CONFIG_FILE_WP <<EOF
<VirtualHost *:80>
ServerName $DOMAIN_NAME
ServerAlias www.$DOMAIN_NAME
DocumentRoot $DOCUMENT_ROOT/$DOMAIN_NAME/
</VirtualHost>
EOF

echo "[ status ] Create Storage Directory For Domain Name ( $DOMAIN_NAME )"
mkdir -m777 $DOCUMENT_ROOT/$DOMAIN_NAME

echo "[ status ] Creating index.html file"
INDEX_HTML_FILE=$DOCUMENT_ROOT/$DOMAIN_NAME/index.html

cat > $INDEX_HTML_FILE <<EOF
<html>
<head><title>$DOMAIN_NAME</title></head>
<body>
<h1>$DOMAIN_NAME</h1>
</body>
</html>
EOF

cd /etc/apache2/sites-available/
echo "[ status ] Disable 000-default.conf"
a2dissite 000-default.conf

echo "[ status ] Enable new config"
a2ensite $CONFIG_FILE

echo "[ status ] Add entry in /etc/hosts"

echo "127.0.0.1 $DOMAIN_NAME" >> /etc/hosts

echo "[ status ] Restarting Apache Service"
service apache2 restart

echo "[ status ] HTTP Storage Created for $DOMAIN_NAME"
echo "[ status ] Open $DOMAIN_NAME in web browser and verify access to index.html"

